In [148]:
import pandas as pd
import numpy as np
from janitor import clean_names #consola : pip install pyjanitor
from unidecode  import unidecode #pip install unidecode

'''
importo el archivo separado por ; y selecciono las columnnas que estamos interesadas
'''
df = pd.read_csv('C:/Users/Jimenean/OneDrive - Edgewell Personal Care/Desktop/PERSONAL/0.CURSOS/0. PROGRAMACIÓN GLOVO/PROYECTO FINAL/airbnb-listings.csv',sep=';') 

df_airbnb = pd.DataFrame(df , columns =['ID','Host ID','Host Since','Host Location','Host Response Time','Host Response Rate',
'Host Listings Count','Host Total Listings Count','Neighbourhood Cleansed', 'Neighbourhood Group Cleansed', 
'City','State', 'Zipcode', 'Market', 'Smart Location', 'Country Code','Country','Latitude', 'Longitude', 
'Property Type', 'Room Type','Accommodates', 'Bathrooms', 'Bedrooms', 'Beds', 'Bed Type','Amenities','Price',
'Weekly Price','Monthly Price','Security Deposit','Cleaning Fee', 'Guests Included', 'Extra People','Minimum Nights','Maximum Nights',
'Number of Reviews','Review Scores Rating', 'Review Scores Accuracy','Review Scores Cleanliness','Review Scores Checkin', 
'Review Scores Communication','Review Scores Location','Review Scores Value', 'Cancellation Policy','Calculated host listings count','Reviews per Month','Features'] )

####################################
#   FAMILIARIZACIÓN DE LOS DATOS   #
####################################

In [149]:
'''
Compruebo el número de columnas y filas que he importado. 
'''

df_airbnb.shape

#print(df_airbnb.head())

#print('filas:',len(df_airbnb.axes[0])," ",'columnas', len(df_airbnb.axes[1]))  #14780 filas & 48 columnas

(14780, 48)

In [150]:

'''
Compruebo los tipos de datos de las columnas y verifico si tienen sentido o hay que modificarlos. 
Cambio Host Since porque aparece como object, lo transformo en fecha 

'''

print(df_airbnb.dtypes) # las que son de tipo character o string en pandas me las marca como object que indica que pueden ser str o mixed. --> OK 

df_airbnb['Host Since'] = pd.to_datetime(df_airbnb['Host Since'], format='%Y-%m-%d') 

print(df_airbnb.dtypes) #Compruebo --> OK

ID                                  int64
Host ID                             int64
Host Since                         object
Host Location                      object
Host Response Time                 object
Host Response Rate                float64
Host Listings Count               float64
Host Total Listings Count         float64
Neighbourhood Cleansed             object
Neighbourhood Group Cleansed       object
City                               object
State                              object
Zipcode                            object
Market                             object
Smart Location                     object
Country Code                       object
Country                            object
Latitude                          float64
Longitude                         float64
Property Type                      object
Room Type                          object
Accommodates                        int64
Bathrooms                         float64
Bedrooms                          float64
Beds                              float64
Bed Type                           object
Amenities                          object
Price                             float64
Weekly Price                      float64
Monthly Price                     float64
Security Deposit                  float64
Cleaning Fee                      float64
Guests Included                     int64
Extra People                        int64
Minimum Nights                      int64
Maximum Nights                      int64
Number of Reviews                   int64
Review Scores Rating              float64
Review Scores Accuracy            float64
Review Scores Cleanliness         float64
Review Scores Checkin             float64
Review Scores Communication       float64
Review Scores Location            float64
Review Scores Value               float64
Cancellation Policy                object
Calculated host listings count    float64
Reviews per Month                 float64
Features                           object
dtype: object
ID                                         int64
Host ID                                    int64
Host Since                        datetime64[ns]
Host Location                             object
Host Response Time                        object
Host Response Rate                       float64
Host Listings Count                      float64
Host Total Listings Count                float64
Neighbourhood Cleansed                    object
Neighbourhood Group Cleansed              object
City                                      object
State                                     object
Zipcode                                   object
Market                                    object
Smart Location                            object
Country Code                              object
Country                                   object
Latitude                                 float64
Longitude                                float64
Property Type                             object
Room Type                                 object
Accommodates                               int64
Bathrooms                                float64
Bedrooms                                 float64
Beds                                     float64
Bed Type                                  object
Amenities                                 object
Price                                    float64
Weekly Price                             float64
Monthly Price                            float64
Security Deposit                         float64
Cleaning Fee                             float64
Guests Included                            int64
Extra People                               int64
Minimum Nights                             int64
Maximum Nights                             int64
Number of Reviews                          int64
Review Scores Rating                     float64
Review Scores Accuracy                   float64
Review Scores Cleanliness                float64
Review Scores Checkin                    float64
Review Scores Communication              float64
Review Scores Location                   float64
Review Scores Value                      float64
Cancellation Policy                       object
Calculated host listings count           float64
Reviews per Month                        float64
Features                                  object
dtype: object

In [151]:
'''
Compruebo si ID es una PK 
'''

print(df_airbnb['ID'].is_unique) # True --> ID es una PK

print(df_airbnb['Host ID'].is_unique) # False , hay host que se repiten --> No sería PK

True
False



#####################################
# NORMALIZACIÓN Y LIMPIEZA DE DATOS #
#####################################

In [152]:
'''
Limpio los nombres de las columnas: Elimino espacios por '_'  y elimino posibles filas vacías
'''

df_airbnb = df_airbnb.clean_names().remove_empty()

'''
Transformo los nombres de columnas a mayúsculas para más legilibilidad 
'''

df_airbnb.columns = map(str.upper, df_airbnb.columns)
df_airbnb

,ID,HOST_ID,HOST_SINCE,HOST_LOCATION,HOST_RESPONSE_TIME,HOST_RESPONSE_RATE,HOST_LISTINGS_COUNT,HOST_TOTAL_LISTINGS_COUNT,NEIGHBOURHOOD_CLEANSED,NEIGHBOURHOOD_GROUP_CLEANSED,...,REVIEW_SCORES_ACCURACY,REVIEW_SCORES_CLEANLINESS,REVIEW_SCORES_CHECKIN,REVIEW_SCORES_COMMUNICATION,REVIEW_SCORES_LOCATION,REVIEW_SCORES_VALUE,CANCELLATION_POLICY,CALCULATED_HOST_LISTINGS_COUNT,REVIEWS_PER_MONTH,FEATURES
0,14712301,7232618,2013-07-02,"Madrid, Community of Madrid, Spain",within a few hours,100.0,1.0,1.0,Kensington and Chelsea,NaN,...,10.0,10.0,9.0,9.0,9.0,10.0,strict,1.0,0.34,"Host Has Profile Pic,Host Identity Verified"
1,12884849,19959228,2014-08-13,GB,NaN,NaN,2.0,2.0,Richmond upon Thames,NaN,...,10.0,9.0,10.0,10.0,10.0,9.0,moderate,2.0,0.76,"Host Has Profile Pic,Is Location Exact"
2,17524980,51343611,2015-12-14,"London, England, United Kingdom",within an hour,90.0,10.0,10.0,Westminster,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,strict,10.0,NaN,"Host Has Profile Pic,Host Identity Verified,In..."
3,3150371,11902716,2014-02-03,"Madrid, Community of Madrid, Spain",within a day,100.0,1.0,1.0,Palacio,Centro,...,10.0,10.0,10.0,10.0,10.0,10.0,flexible,1.0,2.33,"Host Has Profile Pic,Host Identity Verified,Is..."
4,3378181,809083,2011-07-12,"Madrid, Madrid, Spain",within a day,94.0,3.0,3.0,Palacio,Centro,...,10.0,9.0,10.0,10.0,10.0,10.0,strict,2.0,2.69,"Host Has Profile Pic,Host Identity Verified,Is..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14775,15458474,54310958,2016-01-12,"Madrid, Community of Madrid, Spain",within an hour,99.0,207.0,207.0,la Dreta de l'Eixample,Eixample,...,2.0,2.0,2.0,4.0,4.0,2.0,strict,92.0,0.23,"Host Has Profile Pic,Host Identity Verified,Is..."
14776,2545534,3145982,2012-08-03,"Barcelona, Catalonia, Spain",within an hour,100.0,1.0,1.0,la Dreta de l'Eixample,Eixample,...,9.0,9.0,9.0,10.0,10.0,9.0,moderate,1.0,1.78,"Host Has Profile Pic,Host Identity Verified,Is..."
14777,15879739,54310958,2016-01-12,"Madrid, Community of Madrid, Spain",within an hour,99.0,207.0,207.0,"Sant Pere, Santa Caterina i la Ribera",Ciutat Vella,...,NaN,NaN,NaN,NaN,NaN,NaN,strict,92.0,NaN,"Host Has Profile Pic,Host Identity Verified,Is..."
14778,1505984,4212095,2012-11-21,"Barcelona, Cataluña, Spain",within an hour,98.0,14.0,14.0,les Corts,Les Corts,...,9.0,9.0,10.0,10.0,9.0,9.0,moderate,14.0,0.31,"Host Has Profile Pic,Host Identity Verified,Is..."
14779,3449500,13172148,2014-03-16,ES,within an hour,100.0,5.0,5.0,les Corts,Les Corts,...,8.0,8.0,9.0,9.0,9.0,8.0,moderate,5.0,4.80,"Host Has Profile Pic,Host Identity Verified,Is..."


#############################
# LIMPIEZA DE VALORES NULOS #
#############################

In [153]:

'''
Observamos qué columnas son las que más valores nulos contienen y decidimos como tratarlos ya que necesitamos tener un DF sin NANs para que no interfiera luego en el análisis.
Hago esto antes de normalizar/limpiar/transformar los datos a ASCII & Uppercase porque si no pierdo los NaNs
'''

print(df_airbnb.isna().sum())

'''
Para los campos:

- BEDROOMS - 25 Nans
- BEDS - 49
- BATHROOMS -55

- SECURITY DEPOSIT - 8524
- CLEANING_FEE - 6093
- AMENITIES - 170
- FEATURES - 1 

transformaremos el NAN a 0 puesto que el no tener un valor NaN supone que no dispone de esas facilidades, que esa propiedad no tiene coste extra de limpieza o fianza
o que el usuario no ha querido dejar review.

'''

df_airbnb[['BEDROOMS','BEDS','BATHROOMS','SECURITY_DEPOSIT','CLEANING_FEE','AMENITIES', 'FEATURES']] = df_airbnb[['BEDROOMS','BEDS','BATHROOMS','SECURITY_DEPOSIT','CLEANING_FEE','AMENITIES','FEATURES']].fillna(0)



print('**comprobación de NAs en 0 aquí**')
print(df_airbnb.isna().sum())  #Compruebo que me los ha quitado correctamente.

ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                        43
HOST_RESPONSE_TIME                 1899
HOST_RESPONSE_RATE                 1899
HOST_LISTINGS_COUNT                   3
HOST_TOTAL_LISTINGS_COUNT             3
NEIGHBOURHOOD_CLEANSED                0
NEIGHBOURHOOD_GROUP_CLEANSED       1020
CITY                                  6
STATE                               144
ZIPCODE                             506
MARKET                               57
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               1
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                            55
BEDROOMS                             25
BEDS                                 49
BED_TYPE                              0
AMENITIES                           170
PRICE                                17
WEEKLY_PRICE                      11190
MONTHLY_PRICE                     11219
SECURITY_DEPOSIT                   8524
CLEANING_FEE                       6093
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3304
REVIEW_SCORES_ACCURACY             3326
REVIEW_SCORES_CLEANLINESS          3320
REVIEW_SCORES_CHECKIN              3337
REVIEW_SCORES_COMMUNICATION        3320
REVIEW_SCORES_LOCATION             3340
REVIEW_SCORES_VALUE                3341
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        4
REVIEWS_PER_MONTH                  3162
FEATURES                              1
dtype: int64
**comprobación de NAs en 0 aquí**
ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                        43
HOST_RESPONSE_TIME                 1899
HOST_RESPONSE_RATE                 1899
HOST_LISTINGS_COUNT                   3
HOST_TOTAL_LISTINGS_COUNT             3
NEIGHBOURHOOD_CLEANSED                0
NEIGHBOURHOOD_GROUP_CLEANSED       1020
CITY                                  6
STATE                               144
ZIPCODE                             506
MARKET                               57
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               1
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                             0
BEDROOMS                              0
BEDS                                  0
BED_TYPE                              0
AMENITIES                             0
PRICE                                17
WEEKLY_PRICE                      11190
MONTHLY_PRICE                     11219
SECURITY_DEPOSIT                      0
CLEANING_FEE                          0
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3304
REVIEW_SCORES_ACCURACY             3326
REVIEW_SCORES_CLEANLINESS          3320
REVIEW_SCORES_CHECKIN              3337
REVIEW_SCORES_COMMUNICATION        3320
REVIEW_SCORES_LOCATION             3340
REVIEW_SCORES_VALUE                3341
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        4
REVIEWS_PER_MONTH                  3162
FEATURES                              0
dtype: int64

In [154]:
"""
'Review Scores Checkin', 
'Review Scores Communication','Review Scores Location','Review Scores Value'
"""
#MODIFICO VERSIÓN ANTERIOR. DEVUELVO LOS NAN A LAS COLUMNAS REVIEWS.COMPRUEBO LOS NAN DE LAS REVIEWS 

df_airbnb['REVIEW_SCORES_VALUE'].isna().sum()   #3341
df_airbnb['REVIEW_SCORES_CHECKIN'].isna().sum() #3337
df_airbnb['REVIEW_SCORES_COMMUNICATION'].isna().sum() #3320
df_airbnb['REVIEW_SCORES_LOCATION'].isna().sum()  #3340

3340

In [155]:

'''
para los campos:

- WEEKLY PRICE - 11190 Nans
- MONTHLY PRICE - 11219  Nans 

Asumimos que el campo es nulo puesto que el propietario no ofrece de ninguna oferta/descuento de alquiler mensual o semanal. 
Por lo tanto, completaremos ambos campos asumiendo que el coste total sería el precio diario * los dias de alquiler (precio diario * 7 o precio diario * 30) y lo guardaremos en una nueva columna ya limpia 

'''

df_airbnb['WEEKLY_PRICE_CLEANSED'] = np.where(df_airbnb['WEEKLY_PRICE'].isnull(), df_airbnb['PRICE'] * 7, df_airbnb['WEEKLY_PRICE'])

df_airbnb['MONTHLY_PRICE_CLEANSED'] = np.where(df_airbnb['MONTHLY_PRICE'].isnull(), df_airbnb['PRICE'] * 30, df_airbnb['MONTHLY_PRICE'])


print(df_airbnb.columns) #comprobamos que nos ha creado la columna
print(df_airbnb.isna().sum())  #y que no tienen Nans.

Index(['ID', 'HOST_ID', 'HOST_SINCE', 'HOST_LOCATION', 'HOST_RESPONSE_TIME',
       'HOST_RESPONSE_RATE', 'HOST_LISTINGS_COUNT',
       'HOST_TOTAL_LISTINGS_COUNT', 'NEIGHBOURHOOD_CLEANSED',
       'NEIGHBOURHOOD_GROUP_CLEANSED', 'CITY', 'STATE', 'ZIPCODE', 'MARKET',
       'SMART_LOCATION', 'COUNTRY_CODE', 'COUNTRY', 'LATITUDE', 'LONGITUDE',
       'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES', 'BATHROOMS', 'BEDROOMS',
       'BEDS', 'BED_TYPE', 'AMENITIES', 'PRICE', 'WEEKLY_PRICE',
       'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'GUESTS_INCLUDED',
       'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS', 'NUMBER_OF_REVIEWS',
       'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY',
       'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN',
       'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION',
       'REVIEW_SCORES_VALUE', 'CANCELLATION_POLICY',
       'CALCULATED_HOST_LISTINGS_COUNT', 'REVIEWS_PER_MONTH', 'FEATURES',
       'WEEKLY_PRICE_CLEANSED', 'MONTHLY_PRICE_CLEANSED'],
      dtype='object')
ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                        43
HOST_RESPONSE_TIME                 1899
HOST_RESPONSE_RATE                 1899
HOST_LISTINGS_COUNT                   3
HOST_TOTAL_LISTINGS_COUNT             3
NEIGHBOURHOOD_CLEANSED                0
NEIGHBOURHOOD_GROUP_CLEANSED       1020
CITY                                  6
STATE                               144
ZIPCODE                             506
MARKET                               57
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               1
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                             0
BEDROOMS                              0
BEDS                                  0
BED_TYPE                              0
AMENITIES                             0
PRICE                                17
WEEKLY_PRICE                      11190
MONTHLY_PRICE                     11219
SECURITY_DEPOSIT                      0
CLEANING_FEE                          0
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3304
REVIEW_SCORES_ACCURACY             3326
REVIEW_SCORES_CLEANLINESS          3320
REVIEW_SCORES_CHECKIN              3337
REVIEW_SCORES_COMMUNICATION        3320
REVIEW_SCORES_LOCATION             3340
REVIEW_SCORES_VALUE                3341
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        4
REVIEWS_PER_MONTH                  3162
FEATURES                              0
WEEKLY_PRICE_CLEANSED                15
MONTHLY_PRICE_CLEANSED               13
dtype: int64

In [156]:
''' Comprobamos que las nuevas columnas weekly y monthly price cleansed no contienen NaNs
'''
df_airbnb['WEEKLY_PRICE_CLEANSED'].isna
df_airbnb['MONTHLY_PRICE_CLEANSED'].isna

<bound method Series.isna of 0        1500.0
1        5250.0
2        4650.0
3        1080.0
4        1800.0
          ...
14775    2820.0
14776    1800.0
14777    2790.0
14778    3600.0
14779    1470.0
Name: MONTHLY_PRICE_CLEANSED, Length: 14780, dtype: float64>

In [157]:

'''
Miramos también el caso contrario, si PRICE es NaN y WEEKLY_PRICE o MONTHLY_PRICE tienen datos, calculamos la inversa. (Consigo 4 campos más de 17 NaN a 13)
Después de calcular los que faltan, quitamos del modelo los siguen faltando/NaN ya que esté campo es clave para nuestro analisis y no tenemos suficiente información para inferirlo 

'''

df_airbnb['PRICE_CLEANSED'] = np.where(df_airbnb['PRICE'].isnull(), df_airbnb['WEEKLY_PRICE_CLEANSED'] / 7, df_airbnb['PRICE'])
df_airbnb['PRICE_CLEANSED'] = np.where(df_airbnb['PRICE'].isnull(), df_airbnb['MONTHLY_PRICE_CLEANSED'] / 30, df_airbnb['PRICE'])


"""AÑADO LA COLUMNA TOTAL_PRICE QUE SEA LA SUMA DE LA COLUMNA PRICE_CLEANSED Y EL CLEANING FEE
EN ESTE CASO NO INTERESA SUMAR AL PRECIO TOTAL EL DEPÓSITO PORQUE ES UN DINERO RECUPERABLE
"""
#Compruebo que la columna cleaning fee no tiene Nans
df_airbnb['CLEANING_FEE'].isna().sum() # 0 NaN OK

#Realizo la operación
df_airbnb["TOTAL_PRICE"] = df_airbnb["PRICE_CLEANSED"] + df_airbnb["CLEANING_FEE"]


print(df_airbnb.columns) #comprobamos que nos ha creado la columna


#Compruebo que la suma se ha hecho correctamente. Para ello calculo las medias de las columnas
# TOTAL_PRICE y PRICE_CLEANSED  y compruebo que TOTAL_PRICE es superior

df_airbnb['TOTAL_PRICE'].mean() #92.18

df_airbnb['PRICE_CLEANSED'].mean()  #73.60   #OK


df_airbnb.dropna(subset=['PRICE_CLEANSED'],inplace = True) #elimino todas las fillas con NaN, el inplace es para que me lo haga sobre el df.


print(df_airbnb.isna().sum())

Index(['ID', 'HOST_ID', 'HOST_SINCE', 'HOST_LOCATION', 'HOST_RESPONSE_TIME',
       'HOST_RESPONSE_RATE', 'HOST_LISTINGS_COUNT',
       'HOST_TOTAL_LISTINGS_COUNT', 'NEIGHBOURHOOD_CLEANSED',
       'NEIGHBOURHOOD_GROUP_CLEANSED', 'CITY', 'STATE', 'ZIPCODE', 'MARKET',
       'SMART_LOCATION', 'COUNTRY_CODE', 'COUNTRY', 'LATITUDE', 'LONGITUDE',
       'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES', 'BATHROOMS', 'BEDROOMS',
       'BEDS', 'BED_TYPE', 'AMENITIES', 'PRICE', 'WEEKLY_PRICE',
       'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'GUESTS_INCLUDED',
       'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS', 'NUMBER_OF_REVIEWS',
       'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY',
       'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN',
       'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION',
       'REVIEW_SCORES_VALUE', 'CANCELLATION_POLICY',
       'CALCULATED_HOST_LISTINGS_COUNT', 'REVIEWS_PER_MONTH', 'FEATURES',
       'WEEKLY_PRICE_CLEANSED', 'MONTHLY_PRICE_CLEANSED', 'PRICE_CLEANSED',
       'TOTAL_PRICE'],
      dtype='object')
ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                        43
HOST_RESPONSE_TIME                 1898
HOST_RESPONSE_RATE                 1898
HOST_LISTINGS_COUNT                   3
HOST_TOTAL_LISTINGS_COUNT             3
NEIGHBOURHOOD_CLEANSED                0
NEIGHBOURHOOD_GROUP_CLEANSED       1013
CITY                                  6
STATE                               142
ZIPCODE                             505
MARKET                               57
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               1
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                             0
BEDROOMS                              0
BEDS                                  0
BED_TYPE                              0
AMENITIES                             0
PRICE                                 4
WEEKLY_PRICE                      11177
MONTHLY_PRICE                     11206
SECURITY_DEPOSIT                      0
CLEANING_FEE                          0
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3299
REVIEW_SCORES_ACCURACY             3321
REVIEW_SCORES_CLEANLINESS          3315
REVIEW_SCORES_CHECKIN              3332
REVIEW_SCORES_COMMUNICATION        3315
REVIEW_SCORES_LOCATION             3335
REVIEW_SCORES_VALUE                3336
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        4
REVIEWS_PER_MONTH                  3157
FEATURES                              0
WEEKLY_PRICE_CLEANSED                 2
MONTHLY_PRICE_CLEANSED                0
PRICE_CLEANSED                        0
TOTAL_PRICE                           0
dtype: int64

#############################################################################################
# CREAR NUEVA COLUMNA QUE INDIQUE SI LA PROPIEDAD TIENE DESCUENTO POR MEDIA/LARGA TEMPORADA #
############################################################################################

In [158]:
''' Voy a observar unas 5-10 entradas donde no haya valores Nan y ver si generalmente 
los precios weekly y monthly ofrecen descuento, o si simplemente son proporcionales en el tiempo
'''
    #Para ello, creo un df donde elimino los Nan de estas 3 columnas y presento las 10-20 primeras entradas
df_prueba_Nan = df_airbnb[['PRICE', 'WEEKLY_PRICE', 'MONTHLY_PRICE']].dropna()
df_prueba_Nan.head(20)

# Creo yo las mismas columnas calculadas y compruebo si son proporcionales

df_prueba_Nan['WEEKLY_PRICE_CALCULATED']=df_prueba_Nan['PRICE']*7

#Ahora hago una comprobación para ver si generalmente todos los que ofrecen un precio semanal , tienen descuento

df_prueba_Nan["WEEKLY_PRICE_CALCULATED"] > df_prueba_Nan["WEEKLY_PRICE"] 

(df_prueba_Nan["WEEKLY_PRICE_CALCULATED"] > df_prueba_Nan["WEEKLY_PRICE"]).value_counts()

#Hay 2158 apartamentos que muestran descuento semanal frente el diario

#Sin embargo hay 798 registros que el precio semanal no ofrece descuento sobre el diario

#Esto genera dudas. Compruebo los casos en los que el weekly_price sean precios mayores que el PRICE*7
df_prueba_Nan[['WEEKLY_PRICE_CALCULATED','WEEKLY_PRICE']]
df_prueba_Nan[df_prueba_Nan['WEEKLY_PRICE'] > df_prueba_Nan['WEEKLY_PRICE_CALCULATED']]

#Efectivamente hay casos en los que el precio de alquilar la vivienda semanalmente es muy superior que alquilarla por días sueltos
"""
Por ejemplo: 

        PRICE	WEEKLY_PRICE	MONTHLY_PRICE	WEEKLY_PRICE_CALCULATED
19	    95.0	750.0	        3000.0	        665.0
108	    65.0	500.0	        2400.0	        455.0
128	    20.0	273.0	        1092.0	        140.0

"""

#Por lo tanto, calcular los valores de weekly y monthly de manera proporcional al precio diario, no sería lo más acertado


"""Conclusión: Rellenar Nans con valores calculados de PRICE*7 o PRICE*30 no sería muy preciso. Por ello, creamos una nueva
columna, que diga si el HOST presenta descuentos por reservar semanalmente y/o mensualmente. 

    Para ello, crear una nueva columna llamada 'WEEKLY_DISCOUNT' QUE DEVUELVA UN BOOLEANO SI LA COLUMNA 'WEEKLY_PRICE' ES MENOR QUE LA COLUMNA 'PRICE'*7
"""
df_airbnb['WEEKLY_DISCOUNT'] = df_airbnb['WEEKLY_PRICE'] < df_airbnb['PRICE'] * 7

df_airbnb['WEEKLY_DISCOUNT'].value_counts()

#Hay 12148 entradas en las que el ANFITRIÓN ofrece descuento por alquiler semanal 

"""Ahora realizamos lo mismo para los precios mensuales"""

df_airbnb['MONTHLY_CALCULATED']=df_airbnb['PRICE'] * 30

df_airbnb['MONTHLY_DISCOUNT'] = df_airbnb['MONTHLY_PRICE'] < df_airbnb['MONTHLY_CALCULATED']

df_airbnb['MONTHLY_DISCOUNT'].value_counts()


# EN ESTE CASO HAY 3267 ENTRADAS EN LAS QUE EL MONTHLY_PRICE ofrece descuento sobre el diario*30 días

False    11500
True      3267
Name: MONTHLY_DISCOUNT, dtype: int64

In [159]:

'''
otros campos a limpiar

HOST_RESPONSE_RATE - 1899 Nans (cambiar a 0 no tenemos suficientes datos)
HOST_RESPONSE_TIME - 1899 Nans (cambiar a 0 no tenemos suficientes datos)
HOST_LISTINGS_COUNT - 3 Nans (cambiar a 0 no tenemos suficientes datos)
HOST_TOTAL_LISTINGS_COUNT - 3 Nans (cambiar a 0 no tenemos suficientes datos)
CALCULATED_HOST_LISTINGS_COUNT -4 Nans (cambiar a 0 no tenemos suficientes datos)
HOST_SINCE - 3 (cambiar a 0 no tenemos suficientes datos)

No disponemos de suficiente información para inferir el campo por lo que lo transformamos en 0. Posiblemente lo excluiremos del analisis 
'''

df_airbnb['HOST_SINCE'] = df_airbnb['HOST_SINCE'].astype(str) 

df_airbnb[['HOST_SINCE','HOST_RESPONSE_RATE','HOST_RESPONSE_TIME','HOST_LISTINGS_COUNT','HOST_TOTAL_LISTINGS_COUNT','CALCULATED_HOST_LISTINGS_COUNT']] = df_airbnb[['HOST_SINCE','HOST_RESPONSE_RATE','HOST_RESPONSE_TIME','HOST_LISTINGS_COUNT','HOST_TOTAL_LISTINGS_COUNT','CALCULATED_HOST_LISTINGS_COUNT']].fillna(0)


df_airbnb['HOST_SINCE'] = pd.to_datetime(df_airbnb['HOST_SINCE'], format='%Y-%m-%d') #vuelvo a pasarlo a fecha porque al quitarle el NaN me lo ha pasado a object otra vez. Primero he tenido que pasarlo a string porque me daba error


print(df_airbnb.isna().sum())  #Compruebo que me los ha quitado correctamente.

ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                        43
HOST_RESPONSE_TIME                    0
HOST_RESPONSE_RATE                    0
HOST_LISTINGS_COUNT                   0
HOST_TOTAL_LISTINGS_COUNT             0
NEIGHBOURHOOD_CLEANSED                0
NEIGHBOURHOOD_GROUP_CLEANSED       1013
CITY                                  6
STATE                               142
ZIPCODE                             505
MARKET                               57
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               1
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                             0
BEDROOMS                              0
BEDS                                  0
BED_TYPE                              0
AMENITIES                             0
PRICE                                 4
WEEKLY_PRICE                      11177
MONTHLY_PRICE                     11206
SECURITY_DEPOSIT                      0
CLEANING_FEE                          0
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3299
REVIEW_SCORES_ACCURACY             3321
REVIEW_SCORES_CLEANLINESS          3315
REVIEW_SCORES_CHECKIN              3332
REVIEW_SCORES_COMMUNICATION        3315
REVIEW_SCORES_LOCATION             3335
REVIEW_SCORES_VALUE                3336
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        0
REVIEWS_PER_MONTH                  3157
FEATURES                              0
WEEKLY_PRICE_CLEANSED                 2
MONTHLY_PRICE_CLEANSED                0
PRICE_CLEANSED                        0
TOTAL_PRICE                           0
WEEKLY_DISCOUNT                       0
MONTHLY_CALCULATED                    4
MONTHLY_DISCOUNT                      0
dtype: int64


###################################################
# AÑADIENDO COLUMNA DE PRECIO POR PERSONA #
#####################################################

In [160]:
#El valor de la columna se obtiene dividiendo el precio entre las personas que puede acomodar la vivienda

df_airbnb['PRICE_PER_PERSON']=round(df_airbnb["PRICE_CLEANSED"] / df_airbnb["ACCOMMODATES"],2)

##############################################
# AÑADIENDO COLUMNA RATIO CAMA VS PERSONA #
##############################################

In [161]:
df_airbnb['RATIO_BEDS_PERS']=round(df_airbnb["BEDS"] /df_airbnb["ACCOMMODATES"] ,2)

###########################################################
#  AÑADIENDO COLUMNA RATIO  BEDROOMS VS  ACCOMMODATES#
###########################################################

In [162]:
df_airbnb['RATIO_ROOMS_PERS']=round( df_airbnb["BEDROOMS"] / df_airbnb["ACCOMMODATES"],2)

#Hay valores que dan infinito. i.e el caso en el que no hay dormitorios.


#############################
#  LIMPIEZA DE LOCALIZACIÓN #
#############################

In [163]:

'''
Compruebo que columna de localización es más efectiva para filtrar nuestro df por Madrid. Mirando cual tiene menos NaNs y cual identifica mejor Madrid
'''
print(df_airbnb.isna().sum()) #Latitude no tiene ningún NaN, le seguiría City(6) y luego Market (57). NEIGHBOURHOOD_CLEANSED sería el campo para utilizar para Barrio puesto que no tiene NaNs

ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                        43
HOST_RESPONSE_TIME                    0
HOST_RESPONSE_RATE                    0
HOST_LISTINGS_COUNT                   0
HOST_TOTAL_LISTINGS_COUNT             0
NEIGHBOURHOOD_CLEANSED                0
NEIGHBOURHOOD_GROUP_CLEANSED       1013
CITY                                  6
STATE                               142
ZIPCODE                             505
MARKET                               57
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               1
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                             0
BEDROOMS                              0
BEDS                                  0
BED_TYPE                              0
AMENITIES                             0
PRICE                                 4
WEEKLY_PRICE                      11177
MONTHLY_PRICE                     11206
SECURITY_DEPOSIT                      0
CLEANING_FEE                          0
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3299
REVIEW_SCORES_ACCURACY             3321
REVIEW_SCORES_CLEANLINESS          3315
REVIEW_SCORES_CHECKIN              3332
REVIEW_SCORES_COMMUNICATION        3315
REVIEW_SCORES_LOCATION             3335
REVIEW_SCORES_VALUE                3336
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        0
REVIEWS_PER_MONTH                  3157
FEATURES                              0
WEEKLY_PRICE_CLEANSED                 2
MONTHLY_PRICE_CLEANSED                0
PRICE_CLEANSED                        0
TOTAL_PRICE                           0
WEEKLY_DISCOUNT                       0
MONTHLY_CALCULATED                    4
MONTHLY_DISCOUNT                      0
PRICE_PER_PERSON                      0
RATIO_BEDS_PERS                       0
RATIO_ROOMS_PERS                      0
dtype: int64

In [164]:

'''
elimino NEIGHBOURHOOD_GROUP_CLEANSED puesto que tiene muchos NaNs y ya tengo NEIGHBOURHOOD_CLEANSED para poder analizar sin NaNs.
'''

df_airbnb = df_airbnb.drop(columns = ['NEIGHBOURHOOD_GROUP_CLEANSED'])

In [165]:

'''
Transformo todos los NaNs en 0 de momento para poder analizar que campo me interesa más para filtrar mi df por Madrid.

'''

df_airbnb[['HOST_LOCATION','CITY','STATE','ZIPCODE','MARKET','COUNTRY']] = df_airbnb[['HOST_LOCATION','CITY','STATE','ZIPCODE','MARKET','COUNTRY']].fillna(0)


print('**RECUENTO DE COLUMNAS CON NANS**')
print(df_airbnb.isna().sum())

**RECUENTO DE COLUMNAS CON NANS**
ID                                    0
HOST_ID                               0
HOST_SINCE                            3
HOST_LOCATION                         0
HOST_RESPONSE_TIME                    0
HOST_RESPONSE_RATE                    0
HOST_LISTINGS_COUNT                   0
HOST_TOTAL_LISTINGS_COUNT             0
NEIGHBOURHOOD_CLEANSED                0
CITY                                  0
STATE                                 0
ZIPCODE                               0
MARKET                                0
SMART_LOCATION                        0
COUNTRY_CODE                          0
COUNTRY                               0
LATITUDE                              0
LONGITUDE                             0
PROPERTY_TYPE                         0
ROOM_TYPE                             0
ACCOMMODATES                          0
BATHROOMS                             0
BEDROOMS                              0
BEDS                                  0
BED_TYPE                              0
AMENITIES                             0
PRICE                                 4
WEEKLY_PRICE                      11177
MONTHLY_PRICE                     11206
SECURITY_DEPOSIT                      0
CLEANING_FEE                          0
GUESTS_INCLUDED                       0
EXTRA_PEOPLE                          0
MINIMUM_NIGHTS                        0
MAXIMUM_NIGHTS                        0
NUMBER_OF_REVIEWS                     0
REVIEW_SCORES_RATING               3299
REVIEW_SCORES_ACCURACY             3321
REVIEW_SCORES_CLEANLINESS          3315
REVIEW_SCORES_CHECKIN              3332
REVIEW_SCORES_COMMUNICATION        3315
REVIEW_SCORES_LOCATION             3335
REVIEW_SCORES_VALUE                3336
CANCELLATION_POLICY                   0
CALCULATED_HOST_LISTINGS_COUNT        0
REVIEWS_PER_MONTH                  3157
FEATURES                              0
WEEKLY_PRICE_CLEANSED                 2
MONTHLY_PRICE_CLEANSED                0
PRICE_CLEANSED                        0
TOTAL_PRICE                           0
WEEKLY_DISCOUNT                       0
MONTHLY_CALCULATED                    4
MONTHLY_DISCOUNT                      0
PRICE_PER_PERSON                      0
RATIO_BEDS_PERS                       0
RATIO_ROOMS_PERS                      0
dtype: int64

In [166]:

'''
Normalizo y transformo los datos en ASCII para aquellas columnas que son objects - asi podemos tratar mejor y unificar ciudades, barrios etc. 
Primero las transformo en strings ya que al intentar pasarlas a ASCII (unidecode) me da error porque alguna de ellas podrían contener números u otro tipo de datos.
Luego las transformo a ASCII para eliminar acentos, simbolos raros,etc
Luego lo transformo todo a mayúsculas también para que se visualice mejor en Tableau más tarde y para unificar y posiblemente unir campos iguales pero escritos en Mayus/Minus
'''



df_airbnb_string_cols = df_airbnb.select_dtypes(include=['object'], exclude=['datetime64[ns]'])  #Me seguía cogiendo Host Since incluso al haberle cambiado de tipo, lo excluyo a proposito para asegurarme

df_airbnb_string_cols = df_airbnb_string_cols.astype(str)
df_airbnb_string_cols = df_airbnb_string_cols.applymap(lambda x: unidecode(x))
df_airbnb_string_cols = df_airbnb_string_cols.applymap(lambda x: x.upper())
df_airbnb[df_airbnb_string_cols.columns] = df_airbnb_string_cols




print('**RECUENTO DE COLUMNAS AFECTADAS CON LA LIMPIA**') #me aseguro que Host Since no está aquí
print(df_airbnb_string_cols.columns)

**RECUENTO DE COLUMNAS AFECTADAS CON LA LIMPIA**
Index(['HOST_LOCATION', 'HOST_RESPONSE_TIME', 'NEIGHBOURHOOD_CLEANSED', 'CITY',
       'STATE', 'ZIPCODE', 'MARKET', 'SMART_LOCATION', 'COUNTRY_CODE',
       'COUNTRY', 'PROPERTY_TYPE', 'ROOM_TYPE', 'BED_TYPE', 'AMENITIES',
       'CANCELLATION_POLICY', 'FEATURES'],
      dtype='object')

In [167]:

'''State '''

filtered_state = df_airbnb[df_airbnb['STATE'].str.contains("MADR|MAD", case=False)]
count_state = filtered_state['STATE'].count()
print('Hay', count_state, 'resultados para State conteniendo Madr o Mad') #13211

Hay 13205 resultados para State conteniendo Madr o Mad

In [168]:

'''City'''

filtered_city = df_airbnb[df_airbnb['CITY'].str.contains("MADR|MAD", case=False)]
count_city = filtered_city['CITY'].count()
print('Hay', count_city, 'resultados para City conteniendo Madr o Mad') #13247

Hay 13241 resultados para City conteniendo Madr o Mad

In [169]:


'''Smart Location'''

filtered_smart_loc = df_airbnb[df_airbnb['SMART_LOCATION'].str.contains("MADR|MAD", case=False)]
count_smart_loc = filtered_smart_loc['SMART_LOCATION'].count()
print('Hay', count_smart_loc, 'resultados para Smart Location conteniendo Madr o Mad') #13249

Hay 13243 resultados para Smart Location conteniendo Madr o Mad

In [170]:

'''Market'''

filtered_market = df_airbnb[df_airbnb['MARKET'].str.contains("MADR|MAD", case=False)]
count_market= filtered_market['MARKET'].count()
print('Hay', count_market, 'resultados para Market  conteniendo Madr o Mad') #13274

Hay 13268 resultados para Market  conteniendo Madr o Mad

In [171]:

'''
Latitude

todas las latitudes de Madrid empiezan por 40. Esta sería la mejor opción porque aparte de dar más resultados (13405), 
recoge también las ciudades de Madrid que no contienen MADR como Aravaca que hemos visto que el resto de campos no lo recogen bien i.e. City '''

filtered_latitude = df_airbnb[(df_airbnb['LATITUDE'] >= 40.0) & (df_airbnb['LATITUDE'] <= 41.0) ]

count_latitude = filtered_latitude["LATITUDE"].count()

print('Hay', count_latitude, 'resultados para Latitud empezando por 40') #13405 --> la mejor forma de identificar Madrid

Hay 13399 resultados para Latitud empezando por 40

In [172]:

'''
Identificamos aquellos datos que en City o Market no ponía Madrid pero por Latitud si lo son para ver si es un dato que se puede cambiar a Madrid o si por lo contrario se puede descartar.
'''

print(df_airbnb[(df_airbnb['LATITUDE'] >= 40.0) & (df_airbnb['LATITUDE'] <= 41.0) & ~(df_airbnb['CITY'].str.contains("MADR|MAD", case=False))]) # He comprobado en Jupyter Notebook como queda no puedo :( )

             ID    HOST_ID HOST_SINCE                       HOST_LOCATION  \
400    17952035  123181968 2017-03-29                                  CN
401    17824570  116508614 2017-02-15                                CUBA
650    17962836  123330719 2017-03-29                                  CN
654    17455814  104141426 2016-11-17  MADRID, COMMUNITY OF MADRID, SPAIN
812    17962142  123313592 2017-03-29                                  CN
...         ...        ...        ...                                 ...
14763  16709234   32367751 2015-05-01   NEW YORK, NEW YORK, UNITED STATES
14764  16577170    6701890 2013-06-02   NEW YORK, NEW YORK, UNITED STATES
14765    744228     192750 2010-08-05   NEW YORK, NEW YORK, UNITED STATES
14766  13601867    6845704 2013-06-10   NEW YORK, NEW YORK, UNITED STATES
14767  17605828   22015999 2014-10-01  MADRID, COMMUNITY OF MADRID, SPAIN

       HOST_RESPONSE_TIME  HOST_RESPONSE_RATE  HOST_LISTINGS_COUNT  \
400                     0                 0.0                  1.0
401    WITHIN A FEW HOURS                94.0                519.0
650                     0                 0.0                  1.0
654        WITHIN AN HOUR               100.0                  4.0
812                     0                 0.0                  1.0
...                   ...                 ...                  ...
14763  A FEW DAYS OR MORE                40.0                  1.0
14764        WITHIN A DAY                70.0                  1.0
14765  WITHIN A FEW HOURS               100.0                  2.0
14766        WITHIN A DAY                80.0                  2.0
14767  WITHIN A FEW HOURS               100.0                  1.0

       HOST_TOTAL_LISTINGS_COUNT NEIGHBOURHOOD_CLEANSED                CITY  \
400                          1.0   CIUDAD UNIVERSITARIA           MA DE LI
401                        519.0   CIUDAD UNIVERSITARIA           LA HABANA
650                          1.0   CIUDAD UNIVERSITARIA           MA DE LI
654                          4.0                ARAVACA  POZUELO DE ALARCON
812                          1.0            PROSPERIDAD           MA DE LI
...                          ...                    ...                 ...
14763                        1.0           EAST VILLAGE            NEW YORK
14764                        1.0                MIDTOWN            NEW YORK
14765                        2.0                 HARLEM            NEW YORK
14766                        2.0        UPPER EAST SIDE            NEW YORK
14767                        1.0            FORT GREENE            BROOKLYN

       ... WEEKLY_PRICE_CLEANSED MONTHLY_PRICE_CLEANSED PRICE_CLEANSED  \
400    ...                2884.0                12360.0          412.0
401    ...                 714.0                 3060.0          102.0
650    ...                2856.0                12240.0          408.0
654    ...                 175.0                  750.0           25.0
812    ...                2828.0                12120.0          404.0
...    ...                   ...                    ...            ...
14763  ...                 665.0                 2850.0           95.0
14764  ...                 840.0                 3600.0          120.0
14765  ...                1050.0                 3500.0          150.0
14766  ...                1715.0                 7350.0          245.0
14767  ...                1260.0                 5400.0          180.0

      TOTAL_PRICE WEEKLY_DISCOUNT MONTHLY_CALCULATED  MONTHLY_DISCOUNT  \
400         412.0           False            12360.0             False
401         154.0           False             3060.0             False
650         408.0           False            12240.0             False
654          25.0           False              750.0             False
812         404.0           False            12120.0             False
...           ...             ...                ...               ...
14763        95.0           False             2850.0             False
14764       220.0           False             3600.0             False
14765       150.0           False             4500.0              True
14766       315.0           False             7350.0             False
14767       250.0           False             5400.0             False

       PRICE_PER_PERSON RATIO_BEDS_PERS RATIO_ROOMS_PERS
400               206.0            0.50              0.5
401                51.0            0.50              0.5
650               204.0            0.50              0.5
654                25.0            1.00              1.0
812               202.0            0.50              0.5
...                 ...             ...              ...
14763              47.5            0.50              0.5
14764              60.0            0.50              0.5
14765              37.5            0.75              0.5
14766             122.5            0.50              0.5
14767              90.0            0.50              0.5

[158 rows x 57 columns]

In [173]:

'''
Conclusión: Los que no son City Madrid pero Latitud 40, son todos Madrid menos los de State NY , la Latitud está mal puesto que todos son de NY. Se puede filtrar por Country SPAIN para no considerarlos.
Creamos una nueva variable/columna = CITY_CLEANSED, que sea MADRID para todas las latitudes 40 con Country SPAIN, para tener un dato limpio. 
'''

df_airbnb['CITY_CLEANSED'] = np.where((df_airbnb['LATITUDE'] >= 40.0) & (df_airbnb['LATITUDE'] <= 41.0) & (df_airbnb['COUNTRY'] == 'SPAIN'), 'MADRID', df_airbnb['CITY'])


#############################
#  SEPARACIÓN EN COLUMNAS AMENITIES #
#############################

In [174]:

""" Con el objetivo de identificar determinadas amenities de manera sencilla, transformamos todo el texto de la columna a mayúsuclas
"""
df_airbnb['AMENITIES'] = df_airbnb['AMENITIES'].str.upper()

#Una vez está en mayúsculas, creamos una nueva columna ["AMENITIE_INTERNET"] donde devolverá un booleano si la columna "Amenities" original contiene "INTERNET"

#COLUMNA INTERNET BOOLEANA
df_airbnb["INTERNET"] = df_airbnb["AMENITIES"].str.contains("INTERNET")

#COLUMNA AIR CONDITIONING BOOLEANO
df_airbnb["AC"] = df_airbnb["AMENITIES"].str.contains("AIR CONDITIONING")

#COLUMNA 24H_CHECKING BOOLEANO
df_airbnb["24H_CHECKING"] = df_airbnb["AMENITIES"].str.contains("24-HOUR CHECK-IN")

#COLUMNA WASHER BOOLEANO
df_airbnb["WASHER"] = df_airbnb["AMENITIES"].str.contains("WASHER")

#COLUMNA SMOKING ALLOWED BOOLEANO
df_airbnb["SMOKING ALLOWED"] = df_airbnb["AMENITIES"].str.contains("SMOKING ALLOWED")

#COLUMNA PETS ALLOWED BOOLEANO
df_airbnb["PETS ALLOWED"] = df_airbnb["AMENITIES"].str.contains("PETS ALLOWED")

#COLUMNA ELEVATOR BOOLEANO
df_airbnb["ELEVATOR IN BUILDING"] = df_airbnb["AMENITIES"].str.contains("ELEVATOR IN BUILDING")

#AÑADO LAS COLUMNAS DE AMENITIES MÁS POPULARES EN DE BÚSQUEDA EN AIRBNB

In [175]:
#Compruebo que las columnas se han creado correctamente
    #Aleatoriamente:

df_airbnb["ELEVATOR IN BUILDING"]

        #Es correcto

0        False
1        False
2        False
3         True
4         True
         ...
14775     True
14776    False
14777    False
14778     True
14779    False
Name: ELEVATOR IN BUILDING, Length: 14767, dtype: bool

In [176]:
"""
También podemos utilizar la siguiente función para generar estas columnas"""

"""
def find_internet(amenities):
    return "Internet" in amenities

df_airbnb["Internet"] = df_airbnb["Amenities"].apply(find_internet)
"""

'\ndef find_internet(amenities):\n    return "Internet" in amenities\n\ndf_airbnb["Internet"] = df_airbnb["Amenities"].apply(find_internet)\n'


#############################
#  AÑADIENDO COLUMNA BOOLEANA SECUTIRY DEPOSIT #
#############################

In [177]:
"""Crear una columna "SECURITY_DEPOSIT_BOOL" que devuelva un booleano si la columna 
"SECURITY_DEPOSIT" es >0
"""

#Primero compruebo que security_deposit no contiene Nans

df_airbnb['SECURITY_DEPOSIT'].isna().sum()   #0   ok

#Creamos la columna SECURITY_DEPOSIT_BOOL

df_airbnb['SECURITY_DEPOSIT_BOOL'] = df_airbnb['SECURITY_DEPOSIT'] > 0

##########################
#  CODIFICANDO POLÍTICAS DE CANCELACIÓN  #
##########################

In [178]:
df_airbnb['CANCELLATION_POLICY'].unique()

array(['STRICT', 'MODERATE', 'FLEXIBLE', 'SUPER_STRICT_30',
       'FLEXIBLE_NEW', 'SUPER_STRICT_60', 'STRICT_NEW', 'MODERATE_NEW'],
      dtype=object)

In [179]:
#Primero unificamos criterios: Sustituir 'FLEXIBLE_NEW', 'MODERATE_NEW', 'STRICT_NEW' de la column CANCELLATION_POLICY por  'FLEXIBLE' ,'MODERATE', 'STRICT' respectivamente
df_airbnb['CANCELLATION_POLICY'].replace({"FLEXIBLE_NEW": "FLEXIBLE", 
                                          "MODERATE_NEW": "MODERATE", 
                                          "STRICT_NEW": "STRICT"}, inplace=True)

#Comprobamos la sustitución

df_airbnb['CANCELLATION_POLICY'].unique()       #ok

#Hacemos recuento para comprobar posteriormente que la codificación se realiza satisfactoriamente

df_airbnb['CANCELLATION_POLICY'].value_counts()

      #      STRICT             5773
     #        FLEXIBLE           4680
     #       MODERATE           4263
      #      SUPER_STRICT_60      32
       #     SUPER_STRICT_30      19

#Ahora codificamos los niveles

# crear el diccionario de mapeo
map_dict = {'MODERATE': 1, 'STRICT': 2, 'FLEXIBLE': 3, 'SUPER_STRICT_60': 4, 'SUPER_STRICT_30': 5}

# aplicar el método map en la columna "CANCELLATION_POLICY"
df_airbnb['CANCELLATION_POLICY'] = df_airbnb['CANCELLATION_POLICY'].map(map_dict)

#Comprobamos recuento

df_airbnb['CANCELLATION_POLICY'].value_counts()

                #2    5773
                #3    4680
                #1    4263
                #4      32
                #5      19      Correcto

2    5773
3    4680
1    4263
4      32
5      19
Name: CANCELLATION_POLICY, dtype: int64

##########################
#  nueva columna RATIO NVECES ALQUILADO #
##########################

In [180]:
df_airbnb['RATIO_NVECES_ALQUILADO'] = df_airbnb['REVIEWS_PER_MONTH'] / (30/df_airbnb['MINIMUM_NIGHTS'])

df_airbnb['RATIO_NVECES_ALQUILADO']

0        0.056667
1        0.025333
2             NaN
3        0.155333
4        0.269000
           ...
14775    0.015333
14776    0.118667
14777         NaN
14778    0.031000
14779    0.320000
Name: RATIO_NVECES_ALQUILADO, Length: 14767, dtype: float64

In [181]:
df_airbnb.columns

Index(['ID', 'HOST_ID', 'HOST_SINCE', 'HOST_LOCATION', 'HOST_RESPONSE_TIME',
       'HOST_RESPONSE_RATE', 'HOST_LISTINGS_COUNT',
       'HOST_TOTAL_LISTINGS_COUNT', 'NEIGHBOURHOOD_CLEANSED', 'CITY', 'STATE',
       'ZIPCODE', 'MARKET', 'SMART_LOCATION', 'COUNTRY_CODE', 'COUNTRY',
       'LATITUDE', 'LONGITUDE', 'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES',
       'BATHROOMS', 'BEDROOMS', 'BEDS', 'BED_TYPE', 'AMENITIES', 'PRICE',
       'WEEKLY_PRICE', 'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE',
       'GUESTS_INCLUDED', 'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS',
       'NUMBER_OF_REVIEWS', 'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY',
       'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN',
       'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION',
       'REVIEW_SCORES_VALUE', 'CANCELLATION_POLICY',
       'CALCULATED_HOST_LISTINGS_COUNT', 'REVIEWS_PER_MONTH', 'FEATURES',
       'WEEKLY_PRICE_CLEANSED', 'MONTHLY_PRICE_CLEANSED', 'PRICE_CLEANSED',
       'TOTAL_PRICE', 'WEEKLY_DISCOUNT', 'MONTHLY_CALCULATED',
       'MONTHLY_DISCOUNT', 'PRICE_PER_PERSON', 'RATIO_BEDS_PERS',
       'RATIO_ROOMS_PERS', 'CITY_CLEANSED', 'INTERNET', 'AC', '24H_CHECKING',
       'WASHER', 'SMOKING ALLOWED', 'PETS ALLOWED', 'ELEVATOR IN BUILDING',
       'SECURITY_DEPOSIT_BOOL', 'RATIO_NVECES_ALQUILADO'],
      dtype='object')

##########################
#  EXPORTAR EL DF FINAL  #
##########################

In [182]:
'''
Exportamos el df con CITY_CLEANSED = 'MADRID' en formato csv para poder tratarlo en Dveaber y posteriormente Tableau y R. Modifico el separador a comas para que no nos de problemas en el resto de programas
'''

df_airbnb_cleansed = df_airbnb[df_airbnb['CITY_CLEANSED' ] == 'MADRID']

df_airbnb_cleansed.to_csv('df_airbnb_cleansed.csv', index=False, sep=',')

PermissionError: [Errno 13] Permission denied: 'df_airbnb_cleansed.csv'